service: Enhanced-Inventory-Server
frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "ses:SendEmail"
        - "s3:GetObject"
        - "cloudfront:GetDistribution"
      Resource: "*"

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get