version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: erp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: erp_server
      MYSQL_USER: victor
      MYSQL_PASSWORD: 1q2w3e4r
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/erp_server?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: victor
      SPRING_DATASOURCE_PASSWORD: 1q2w3e4r
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local